project_name: spellshape
builds:
  - main: ./spellshape/cmd/spellshape
    ldflags:
      - -s -w -X github.com/spellshape/cli/spellshape/version.Version={{.Tag}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
