name: Docs Deploy

on:
  push:
    branches:
      - main

jobs:
  consecutiveness:
    runs-on: ubuntu-latest
    steps:
      - uses: mktcode/consecutive-workflow-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: [consecutiveness]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: docs/node_modules
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: docs/yarn.lock

      - name: Install Dependencies
        run: yarn install
        working-directory: ./docs

      - name: Build
        run: yarn run build
        working-directory: ./docs

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_IGNTSERVICES }}'
          channelId: live
          target: docs.spellshape.com
          projectId: igntservices
