name: Docs Deploy Preview

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  build_and_deploy:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: docs/node_modules
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: docs/yarn.lock

      - name: Install Dependencies
        run: yarn install
        working-directory: ./docs

      - name: Build
        run: yarn run build
        working-directory: ./docs

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_IGNTSERVICES }}'
          expires: 7d
          target: docs.spellshape.com
          projectId: igntservices
          firebaseToolsVersion: v11.12.0
