name: Release nightly

on:
  push:
    branches:
      - main

jobs:
  consecutiveness:
    runs-on: ubuntu-latest
    steps:
      - uses: mktcode/consecutive-workflow-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  release-nightly:
    runs-on: ubuntu-latest
    needs: [consecutiveness]
    env:
      working-directory: go/src/github.com/spellshape/cli

    steps:
      - uses: actions/checkout@v3

      - name: Delete the nightly release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: nightly
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push new nightly tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: nightly
          tag_prefix: ''

      - name: Create the new nightly release
        uses: ncipollo/release-action@v1
        with:
          tag: nightly
          name: nightly
          body: 'Install and move the CLI to your bin directory: `curl https://get.spellshape.com/spellshape/cli@nightly! | bash`'
          prerelease: true

  releases-binaries:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.34
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_path: './spellshape/cmd/spellshape'
          binary_name: 'spellshape'
          asset_name: spellshape-nightly-${{ matrix.goos }}-${{ matrix.goarch }}
          release_name: 'nightly'
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: -s -w -X github.com/spellshape/cli/spellshape/version.Version=nightly
          goversion: '1.19'
          retry: 10
